import {
  Megaphone,
  DollarSign,
  Database,
  PenTool,
  Users,
  Code,
  GanttChart,
  Scale,
  PiggyBank,
  BookOpen,
  FlaskConical,
  CalendarDays,
  Palette,
  Settings,
  Boxes,
  ShieldCheck,
  Briefcase,
  Stethoscope,
  MessageSquareText,
  Workflow,
} from "lucide-react";

export const templates = [
  {
    id: "1",
    name: "Marketing Pro",
    description: "Generates marketing copy, analyzes data, and suggests campaigns.",
    Icon: Megaphone,
    category: "Marketing",
    exampleTasks: [
      "Analyze recent campaign data for our new product.",
      "Suggest three new marketing slogans.",
      "Draft a promotional email for our upcoming sale.",
    ],
    backendTask: "analyzeMarketingData",
  },
  {
    id: "2",
    name: "Sales Sidekick",
    description: "Automates sales outreach, tracks leads, and manages contacts.",
    Icon: DollarSign,
    category: "Sales",
    exampleTasks: [
      "Draft a follow-up email to the lead from yesterday.",
      "Find 5 potential leads in the tech industry.",
      "Update the contact information for our new client.",
    ],
    backendTask: "automateSalesOutreach",
  },
  {
    id: "3",
    name: "Support Specialist",
    description: "Handles customer support tickets and provides assistance.",
    Icon: MessageSquareText,
    category: "Support",
    exampleTasks: [
      "Respond to the customer ticket regarding a billing issue.",
      "Escalate the technical issue to the engineering team.",
      "Provide a step-by-step guide for resetting a password.",
    ],
    backendTask: "handleSupportTicket",
  },
  {
    id: "4",
    name: "Business Analyst",
    description: "Analyzes business data to find actionable insights.",
    Icon: Database,
    category: "Business",
    exampleTasks: [
      "Analyze the sales data from the last quarter.",
      "Generate a report on customer demographics.",
      "Identify trends in our website traffic.",
    ],
    backendTask: "analyzeBusinessData",
  },
  {
    id: "5",
    name: "HR Helper",
    description: "Automates repetitive HR tasks and manages employee data.",
    Icon: Users,
    category: "HR",
    exampleTasks: [
      "Draft a job description for a new software engineer role.",
      "Schedule interviews with the top three candidates.",
      "Onboard the new employee and grant them access to our systems.",
    ],
    backendTask: "automateHrTasks",
  },
  {
    id: "6",
    name: "Code Companion",
    description: "Generates code snippets and assists with development tasks.",
    Icon: Code,
    category: "Development",
    exampleTasks: [
      "Write a Python script to scrape data from a website.",
      "Generate a React component for a user profile page.",
      "Debug the error in our login form.",
    ],
    backendTask: "generateCode",
  },
  {
    id: "7",
    name: "Project Planner",
    description: "Manages and prioritizes project tasks, deadlines, and resources.",
    Icon: GanttChart,
    category: "Project Management",
    exampleTasks: [
      "Create a project plan for our new mobile app.",
      "Assign tasks to team members and set deadlines.",
      "Track the progress of our current sprint.",
    ],
    backendTask: "manageProjectTasks",
  },
  {
    id: "8",
    name: "Legal Eagle",
    description: "Reviews legal documents and provides analysis.",
    Icon: Scale,
    category: "Legal",
    exampleTasks: [
      "Review our new terms of service for potential issues.",
      "Summarize the key points of this contract.",
      "Draft a non-disclosure agreement for a new contractor.",
    ],
    backendTask: "analyzeLegalDocument",
  },
  {
    id: "9",
    name: "Finance Guru",
    description: "Analyzes financial data and generates reports.",
    Icon: PiggyBank,
    category: "Finance",
    exampleTasks: [
      "Analyze our spending from the last quarter.",
      "Generate a financial report for our investors.",
      "Create a budget for the upcoming fiscal year.",
    ],
    backendTask: "analyzeFinancialData",
  },
  {
    id: "10",
    name: "Personal Assistant",
    description: "Organizes and manages personal tasks and schedules.",
    Icon: CalendarDays,
    category: "Personal",
    exampleTasks: [
      "Schedule a meeting with my team for tomorrow afternoon.",
      "Remind me to call my dentist next week.",
      "Book a flight to New York for next month.",
    ],
    backendTask: "managePersonalTasks",
  },
  {
    id: "11",
    name: "IT Troubleshooter",
    description: "Troubleshoots and resolves IT issues.",
    Icon: Settings,
    category: "IT",
    exampleTasks: [
      "Troubleshoot my slow internet connection.",
      "Reset my password for the company VPN.",
      "Install the latest software updates on my computer.",
    ],
    backendTask: "resolveItIssue",
  },
  {
    id: "12",
    name: "Supply Chain Optimizer",
    description: "Optimizes a supply chain for efficiency and cost savings.",
    Icon: Boxes,
    category: "Operations",
    exampleTasks: [
      "Analyze our current shipping routes and suggest improvements.",
      "Find a new supplier for our raw materials.",
      "Track our inventory levels and reorder products as needed.",
    ],
    backendTask: "optimizeSupplyChain",
  },
  {
    id: "13",
    name: "Security Sentinel",
    description: "Analyzes potential security threats and recommends actions.",
    Icon: ShieldCheck,
    category: "Security",
    exampleTasks: [
      "Investigate the suspicious email I received this morning.",
      "Scan our website for vulnerabilities.",
      "Recommend a new security protocol for our team.",
    ],
    backendTask: "analyzeSecurityThreat",
  },
  {
    id: "14",
    name: "Product Pioneer",
    description: "Analyzes customer feedback for product improvement ideas.",
    Icon: FlaskConical,
    category: "Product",
    exampleTasks: [
      "Summarize the customer feedback from our latest survey.",
      "Suggest three new features for our mobile app.",
      "Prioritize the bug fixes for our next release.",
    ],
    backendTask: "analyzeProductFeedback",
  },
  {
    id: "15",
    name: "Healthcare Hero",
    description: "Manages and updates patient medical records.",
    Icon: Stethoscope,
    category: "Healthcare",
    exampleTasks: [
      "Update the patient\'s medical history with their latest test results.",
      "Schedule a follow-up appointment for the patient.",
      "Create a summary of the patient\'s recent visit.",
    ],
    backendTask: "managePatientRecords",
  },
  {
    id: "16",
    name: "AI Team Orchestrator",
    description: "Orchestrates a team of AI agents to accomplish a goal.",
    Icon: Workflow,
    category: "AI",
    exampleTasks: [
      "Coordinate the marketing and sales teams to launch a new product.",
      "Assign tasks to the appropriate AI agent to resolve a customer issue.",
      "Monitor the performance of the AI team and make adjustments as needed.",
    ],
    backendTask: "orchestrateAiTeam",
  },
];
