// PowerUps Catalog - Monthly add-on subscriptions
// Each powerup is billed separately at its listed price

export interface PowerUp {
  id: string;
  name: string;
  description: string;
  category: 'analytics' | 'automation' | 'integration' | 'ai' | 'security' | 'communication' | 'productivity' | 'data';
  price: number; // Monthly price in USD
  features: string[];
  icon: string; // Lucide icon name
  popular?: boolean;
  new?: boolean;
}

export const powerUpsCatalog: PowerUp[] = [
  // === ANALYTICS POWERUPS ===
  {
    id: 'anomaly-detection',
    name: 'AI Anomaly Detection',
    description: 'Automatically detect unusual patterns and anomalies in your business data with machine learning.',
    category: 'analytics',
    price: 9,
    features: ['Real-time monitoring', 'Custom alert thresholds', 'Pattern recognition', 'Slack/Email alerts'],
    icon: 'AlertTriangle',
    popular: true,
  },
  {
    id: 'predictive-analytics',
    name: 'Predictive Analytics',
    description: 'Forecast future trends, sales, and outcomes using advanced AI models.',
    category: 'analytics',
    price: 19,
    features: ['Revenue forecasting', 'Trend prediction', 'Churn prediction', 'Custom models'],
    icon: 'TrendingUp',
    popular: true,
  },
  {
    id: 'advanced-reporting',
    name: 'Advanced Reports',
    description: 'Generate comprehensive PDF and Excel reports automatically on a schedule.',
    category: 'analytics',
    price: 7,
    features: ['Scheduled reports', 'PDF/Excel export', 'Custom branding', 'Email delivery'],
    icon: 'FileText',
  },
  {
    id: 'competitor-tracking',
    name: 'Competitor Intelligence',
    description: 'Track competitor pricing, features, and marketing moves automatically.',
    category: 'analytics',
    price: 29,
    features: ['Price monitoring', 'Feature tracking', 'Social media analysis', 'Weekly digests'],
    icon: 'Eye',
    new: true,
  },
  {
    id: 'sentiment-analysis',
    name: 'Sentiment Analysis',
    description: 'Analyze customer sentiment across reviews, social media, and support tickets.',
    category: 'analytics',
    price: 12,
    features: ['Review analysis', 'Social listening', 'Trend detection', 'Sentiment scores'],
    icon: 'Heart',
  },

  // === AUTOMATION POWERUPS ===
  {
    id: 'workflow-automation',
    name: 'Workflow Automation',
    description: 'Create complex multi-step workflows that run automatically based on triggers.',
    category: 'automation',
    price: 15,
    features: ['Visual workflow builder', 'Conditional logic', 'Multi-step actions', 'Error handling'],
    icon: 'GitBranch',
    popular: true,
  },
  {
    id: 'scheduled-tasks',
    name: 'Advanced Scheduling',
    description: 'Schedule any AI employee task to run at specific times or intervals.',
    category: 'automation',
    price: 5,
    features: ['Cron scheduling', 'Timezone support', 'Retry logic', 'Execution logs'],
    icon: 'Clock',
  },
  {
    id: 'auto-responder',
    name: 'Smart Auto-Responder',
    description: 'Automatically respond to emails and messages when you\'re away.',
    category: 'automation',
    price: 8,
    features: ['AI-powered replies', 'Custom rules', 'Out-of-office mode', 'Priority detection'],
    icon: 'Mail',
  },
  {
    id: 'data-sync',
    name: 'Bi-Directional Sync',
    description: 'Keep data synchronized across multiple platforms automatically.',
    category: 'automation',
    price: 12,
    features: ['Real-time sync', 'Conflict resolution', 'Audit trail', 'Rollback support'],
    icon: 'RefreshCw',
  },
  {
    id: 'approval-workflows',
    name: 'Approval Workflows',
    description: 'Set up approval chains for content, expenses, and decisions.',
    category: 'automation',
    price: 10,
    features: ['Multi-level approvals', 'Mobile notifications', 'Deadline tracking', 'Delegation'],
    icon: 'CheckSquare',
    new: true,
  },

  // === INTEGRATION POWERUPS ===
  {
    id: 'slack-integration',
    name: 'Slack Deep Integration',
    description: 'Full Slack integration with commands, notifications, and AI chat in channels.',
    category: 'integration',
    price: 7,
    features: ['Slash commands', 'Channel notifications', 'AI in threads', 'Status sync'],
    icon: 'MessageSquare',
  },
  {
    id: 'google-workspace',
    name: 'Google Workspace Sync',
    description: 'Connect Gmail, Calendar, Drive, and Sheets for seamless integration.',
    category: 'integration',
    price: 9,
    features: ['Gmail integration', 'Calendar sync', 'Drive access', 'Sheets automation'],
    icon: 'Cloud',
    popular: true,
  },
  {
    id: 'salesforce-connector',
    name: 'Salesforce Connector',
    description: 'Two-way integration with Salesforce CRM for leads, opportunities, and contacts.',
    category: 'integration',
    price: 19,
    features: ['Lead sync', 'Opportunity tracking', 'Contact management', 'Custom objects'],
    icon: 'Database',
  },
  {
    id: 'hubspot-connector',
    name: 'HubSpot Connector',
    description: 'Connect with HubSpot for marketing, sales, and service automation.',
    category: 'integration',
    price: 15,
    features: ['Contact sync', 'Deal tracking', 'Email sequences', 'Form submissions'],
    icon: 'Target',
  },
  {
    id: 'zapier-bridge',
    name: 'Zapier Bridge',
    description: 'Connect Auraa AI to 5000+ apps through Zapier.',
    category: 'integration',
    price: 12,
    features: ['Bi-directional triggers', 'Custom actions', 'Multi-step zaps', 'Data mapping'],
    icon: 'Zap',
    popular: true,
  },
  {
    id: 'webhook-pro',
    name: 'Webhook Pro',
    description: 'Advanced webhook management with retries, signatures, and debugging.',
    category: 'integration',
    price: 6,
    features: ['Webhook debugging', 'Signature verification', 'Retry logic', 'Request logging'],
    icon: 'Webhook',
  },

  // === AI POWERUPS ===
  {
    id: 'gpt4-turbo',
    name: 'GPT-4 Turbo Access',
    description: 'Upgrade AI employees to use GPT-4 Turbo for more complex tasks.',
    category: 'ai',
    price: 25,
    features: ['128K context window', 'Faster responses', 'Better reasoning', 'Code generation'],
    icon: 'Sparkles',
    popular: true,
  },
  {
    id: 'claude-opus',
    name: 'Claude Opus Upgrade',
    description: 'Access Anthropic\'s most powerful Claude model for premium tasks.',
    category: 'ai',
    price: 29,
    features: ['Superior analysis', 'Long documents', 'Complex reasoning', 'Better safety'],
    icon: 'Brain',
    new: true,
  },
  {
    id: 'custom-training',
    name: 'Custom AI Training',
    description: 'Train AI employees on your specific documents, style, and knowledge.',
    category: 'ai',
    price: 39,
    features: ['Document ingestion', 'Style learning', 'FAQ training', 'Terminology'],
    icon: 'GraduationCap',
  },
  {
    id: 'vision-ai',
    name: 'Vision AI',
    description: 'Enable AI employees to analyze images, charts, and screenshots.',
    category: 'ai',
    price: 15,
    features: ['Image analysis', 'Chart reading', 'OCR extraction', 'Visual QA'],
    icon: 'ScanEye',
    new: true,
  },
  {
    id: 'voice-ai',
    name: 'Voice AI',
    description: 'Talk to AI employees with voice commands and get audio responses.',
    category: 'ai',
    price: 12,
    features: ['Voice input', 'Audio responses', 'Transcription', 'Phone integration'],
    icon: 'Mic',
  },

  // === SECURITY POWERUPS ===
  {
    id: 'sso-saml',
    name: 'SSO/SAML',
    description: 'Enterprise single sign-on with SAML 2.0 and SCIM provisioning.',
    category: 'security',
    price: 29,
    features: ['SAML 2.0', 'SCIM provisioning', 'JIT user creation', 'Custom domains'],
    icon: 'Shield',
  },
  {
    id: 'audit-logs',
    name: 'Advanced Audit Logs',
    description: 'Detailed audit trails with export, search, and compliance reports.',
    category: 'security',
    price: 12,
    features: ['90-day retention', 'Export to SIEM', 'Compliance reports', 'User activity'],
    icon: 'FileSearch',
  },
  {
    id: 'data-encryption',
    name: 'Data Encryption Plus',
    description: 'Customer-managed encryption keys and additional data protection.',
    category: 'security',
    price: 19,
    features: ['BYOK encryption', 'Field-level encryption', 'Data masking', 'Key rotation'],
    icon: 'Lock',
  },
  {
    id: 'ip-restrictions',
    name: 'IP Restrictions',
    description: 'Restrict access to your workspace by IP address or range.',
    category: 'security',
    price: 8,
    features: ['IP allowlisting', 'VPN support', 'Geo-blocking', 'Access logs'],
    icon: 'Globe',
  },

  // === COMMUNICATION POWERUPS ===
  {
    id: 'white-label-email',
    name: 'White Label Email',
    description: 'Send emails from AI employees using your own domain and branding.',
    category: 'communication',
    price: 15,
    features: ['Custom domain', 'DKIM/SPF setup', 'Email templates', 'Tracking'],
    icon: 'Mail',
    popular: true,
  },
  {
    id: 'sms-notifications',
    name: 'SMS Notifications',
    description: 'Send and receive SMS messages through AI employees.',
    category: 'communication',
    price: 10,
    features: ['Two-way SMS', 'Global coverage', 'Auto-responses', 'Bulk messaging'],
    icon: 'Smartphone',
  },
  {
    id: 'video-meetings',
    name: 'Video Meeting AI',
    description: 'AI assistant joins video calls to take notes and action items.',
    category: 'communication',
    price: 19,
    features: ['Meeting notes', 'Action items', 'Transcription', 'Summary emails'],
    icon: 'Video',
    new: true,
  },
  {
    id: 'multi-language',
    name: 'Multi-Language Support',
    description: 'AI employees can communicate in 50+ languages.',
    category: 'communication',
    price: 12,
    features: ['50+ languages', 'Auto-detection', 'Translation', 'Localization'],
    icon: 'Languages',
  },

  // === PRODUCTIVITY POWERUPS ===
  {
    id: 'priority-queue',
    name: 'Priority Queue',
    description: 'Your tasks get processed first with dedicated compute resources.',
    category: 'productivity',
    price: 15,
    features: ['Priority processing', 'Faster responses', 'No queuing', 'Guaranteed SLA'],
    icon: 'Gauge',
    popular: true,
  },
  {
    id: 'unlimited-history',
    name: 'Unlimited History',
    description: 'Access your complete conversation and task history forever.',
    category: 'productivity',
    price: 7,
    features: ['Unlimited retention', 'Search history', 'Export all data', 'Analytics'],
    icon: 'History',
  },
  {
    id: 'templates-pro',
    name: 'Templates Pro',
    description: 'Access premium task templates and create your own.',
    category: 'productivity',
    price: 5,
    features: ['100+ templates', 'Custom templates', 'Team sharing', 'Variables'],
    icon: 'LayoutTemplate',
  },
  {
    id: 'team-collaboration',
    name: 'Team Collaboration',
    description: 'Share AI employees and collaborate with your team.',
    category: 'productivity',
    price: 19,
    features: ['Shared employees', 'Team dashboard', 'Role permissions', 'Activity feed'],
    icon: 'Users',
    new: true,
  },
  {
    id: 'mobile-app',
    name: 'Mobile App Access',
    description: 'Access AI employees from dedicated iOS and Android apps.',
    category: 'productivity',
    price: 5,
    features: ['iOS app', 'Android app', 'Push notifications', 'Offline mode'],
    icon: 'Smartphone',
  },

  // === DATA POWERUPS ===
  {
    id: 'data-warehouse',
    name: 'Data Warehouse Sync',
    description: 'Connect to Snowflake, BigQuery, or Redshift for enterprise data.',
    category: 'data',
    price: 39,
    features: ['Snowflake', 'BigQuery', 'Redshift', 'Custom queries'],
    icon: 'Database',
  },
  {
    id: 'api-pro',
    name: 'API Pro',
    description: 'Higher API limits, dedicated endpoints, and priority support.',
    category: 'data',
    price: 25,
    features: ['10x rate limits', 'Dedicated endpoints', 'Batch operations', 'GraphQL'],
    icon: 'Code',
  },
  {
    id: 'data-import',
    name: 'Bulk Data Import',
    description: 'Import large datasets from CSV, Excel, or databases.',
    category: 'data',
    price: 8,
    features: ['CSV/Excel import', 'Data mapping', 'Deduplication', 'Validation'],
    icon: 'Upload',
  },
  {
    id: 'real-time-sync',
    name: 'Real-Time Data Sync',
    description: 'Stream data changes in real-time from external databases.',
    category: 'data',
    price: 29,
    features: ['CDC streaming', 'Low latency', 'Schema evolution', 'Backfill'],
    icon: 'Activity',
  },
];

export const powerUpCategories = [
  { id: 'all', name: 'All Power-Ups', icon: 'Grid' },
  { id: 'analytics', name: 'Analytics', icon: 'BarChart3' },
  { id: 'automation', name: 'Automation', icon: 'Workflow' },
  { id: 'integration', name: 'Integrations', icon: 'Plug' },
  { id: 'ai', name: 'AI Upgrades', icon: 'Brain' },
  { id: 'security', name: 'Security', icon: 'Shield' },
  { id: 'communication', name: 'Communication', icon: 'MessageCircle' },
  { id: 'productivity', name: 'Productivity', icon: 'Rocket' },
  { id: 'data', name: 'Data', icon: 'Database' },
];
