extend type Mutation {
  """
  ✨ Insert a single `AgentTask` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  agentTask_insert(
    """
    Data object to insert into the table.
    """
    data: AgentTask_Data!
  ): AgentTask_KeyOutput! @fdc_generated(from: "AgentTask", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `AiEmployee` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  aiEmployee_insert(
    """
    Data object to insert into the table.
    """
    data: AiEmployee_Data!
  ): AiEmployee_KeyOutput! @fdc_generated(from: "AiEmployee", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `AiEmployeeSkill` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  aiEmployeeSkill_insert(
    """
    Data object to insert into the table.
    """
    data: AiEmployeeSkill_Data!
  ): AiEmployeeSkill_KeyOutput! @fdc_generated(from: "AiEmployeeSkill", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `BusinessGoal` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  businessGoal_insert(
    """
    Data object to insert into the table.
    """
    data: BusinessGoal_Data!
  ): BusinessGoal_KeyOutput! @fdc_generated(from: "BusinessGoal", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `DeploymentRequest` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  deploymentRequest_insert(
    """
    Data object to insert into the table.
    """
    data: DeploymentRequest_Data!
  ): DeploymentRequest_KeyOutput! @fdc_generated(from: "DeploymentRequest", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Purchase` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  purchase_insert(
    """
    Data object to insert into the table.
    """
    data: Purchase_Data!
  ): Purchase_KeyOutput! @fdc_generated(from: "Purchase", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Review` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  review_insert(
    """
    Data object to insert into the table.
    """
    data: Review_Data!
  ): Review_KeyOutput! @fdc_generated(from: "Review", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `SharedKnowledge` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sharedKnowledge_insert(
    """
    Data object to insert into the table.
    """
    data: SharedKnowledge_Data!
  ): SharedKnowledge_KeyOutput! @fdc_generated(from: "SharedKnowledge", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Skill` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  skill_insert(
    """
    Data object to insert into the table.
    """
    data: Skill_Data!
  ): Skill_KeyOutput! @fdc_generated(from: "Skill", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Task` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  task_insert(
    """
    Data object to insert into the table.
    """
    data: Task_Data!
  ): Task_KeyOutput! @fdc_generated(from: "Task", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `AgentTask` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  agentTask_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [AgentTask_Data!]!
  ): [AgentTask_KeyOutput!]! @fdc_generated(from: "AgentTask", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `AiEmployee` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  aiEmployee_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [AiEmployee_Data!]!
  ): [AiEmployee_KeyOutput!]! @fdc_generated(from: "AiEmployee", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `AiEmployeeSkill` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  aiEmployeeSkill_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [AiEmployeeSkill_Data!]!
  ): [AiEmployeeSkill_KeyOutput!]! @fdc_generated(from: "AiEmployeeSkill", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `BusinessGoal` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  businessGoal_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [BusinessGoal_Data!]!
  ): [BusinessGoal_KeyOutput!]! @fdc_generated(from: "BusinessGoal", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `DeploymentRequest` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  deploymentRequest_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [DeploymentRequest_Data!]!
  ): [DeploymentRequest_KeyOutput!]! @fdc_generated(from: "DeploymentRequest", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Purchase` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  purchase_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Purchase_Data!]!
  ): [Purchase_KeyOutput!]! @fdc_generated(from: "Purchase", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Review` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  review_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Review_Data!]!
  ): [Review_KeyOutput!]! @fdc_generated(from: "Review", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `SharedKnowledge` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  sharedKnowledge_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [SharedKnowledge_Data!]!
  ): [SharedKnowledge_KeyOutput!]! @fdc_generated(from: "SharedKnowledge", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Skill` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  skill_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Skill_Data!]!
  ): [Skill_KeyOutput!]! @fdc_generated(from: "Skill", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Task` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  task_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Task_Data!]!
  ): [Task_KeyOutput!]! @fdc_generated(from: "Task", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `AgentTask` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AgentTask`.
  """
  agentTask_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: AgentTask_Data!
  ): AgentTask_KeyOutput! @fdc_generated(from: "AgentTask", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `AiEmployee` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AiEmployee`.
  """
  aiEmployee_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: AiEmployee_Data!
  ): AiEmployee_KeyOutput! @fdc_generated(from: "AiEmployee", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `AiEmployeeSkill` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AiEmployeeSkill`.
  """
  aiEmployeeSkill_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: AiEmployeeSkill_Data!
  ): AiEmployeeSkill_KeyOutput! @fdc_generated(from: "AiEmployeeSkill", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `BusinessGoal` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `BusinessGoal`.
  """
  businessGoal_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: BusinessGoal_Data!
  ): BusinessGoal_KeyOutput! @fdc_generated(from: "BusinessGoal", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `DeploymentRequest` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DeploymentRequest`.
  """
  deploymentRequest_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: DeploymentRequest_Data!
  ): DeploymentRequest_KeyOutput! @fdc_generated(from: "DeploymentRequest", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Purchase` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Purchase`.
  """
  purchase_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Purchase_Data!
  ): Purchase_KeyOutput! @fdc_generated(from: "Purchase", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Review` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Review`.
  """
  review_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Review_Data!
  ): Review_KeyOutput! @fdc_generated(from: "Review", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `SharedKnowledge` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SharedKnowledge`.
  """
  sharedKnowledge_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: SharedKnowledge_Data!
  ): SharedKnowledge_KeyOutput! @fdc_generated(from: "SharedKnowledge", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Skill` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Skill`.
  """
  skill_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Skill_Data!
  ): Skill_KeyOutput! @fdc_generated(from: "Skill", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Task` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Task`.
  """
  task_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Task_Data!
  ): Task_KeyOutput! @fdc_generated(from: "Task", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `AgentTask` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AgentTask`.
  """
  agentTask_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [AgentTask_Data!]!
  ): [AgentTask_KeyOutput!]! @fdc_generated(from: "AgentTask", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `AiEmployee` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AiEmployee`.
  """
  aiEmployee_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [AiEmployee_Data!]!
  ): [AiEmployee_KeyOutput!]! @fdc_generated(from: "AiEmployee", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `AiEmployeeSkill` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AiEmployeeSkill`.
  """
  aiEmployeeSkill_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [AiEmployeeSkill_Data!]!
  ): [AiEmployeeSkill_KeyOutput!]! @fdc_generated(from: "AiEmployeeSkill", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `BusinessGoal` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `BusinessGoal`.
  """
  businessGoal_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [BusinessGoal_Data!]!
  ): [BusinessGoal_KeyOutput!]! @fdc_generated(from: "BusinessGoal", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `DeploymentRequest` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DeploymentRequest`.
  """
  deploymentRequest_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [DeploymentRequest_Data!]!
  ): [DeploymentRequest_KeyOutput!]! @fdc_generated(from: "DeploymentRequest", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Purchase` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Purchase`.
  """
  purchase_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Purchase_Data!]!
  ): [Purchase_KeyOutput!]! @fdc_generated(from: "Purchase", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Review` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Review`.
  """
  review_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Review_Data!]!
  ): [Review_KeyOutput!]! @fdc_generated(from: "Review", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `SharedKnowledge` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SharedKnowledge`.
  """
  sharedKnowledge_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [SharedKnowledge_Data!]!
  ): [SharedKnowledge_KeyOutput!]! @fdc_generated(from: "SharedKnowledge", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Skill` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Skill`.
  """
  skill_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Skill_Data!]!
  ): [Skill_KeyOutput!]! @fdc_generated(from: "Skill", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Task` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Task`.
  """
  task_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Task_Data!]!
  ): [Task_KeyOutput!]! @fdc_generated(from: "Task", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `AgentTask` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `AgentTask` or `null` if not found.
  """
  agentTask_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AgentTask_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AgentTask_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: AgentTask_Data!
  ): AgentTask_KeyOutput @fdc_generated(from: "AgentTask", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `AiEmployee` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `AiEmployee` or `null` if not found.
  """
  aiEmployee_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AiEmployee_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AiEmployee_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: AiEmployee_Data!
  ): AiEmployee_KeyOutput @fdc_generated(from: "AiEmployee", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `AiEmployeeSkill` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `AiEmployeeSkill` or `null` if not found.
  """
  aiEmployeeSkill_update(
    """
    The key used to identify the object.
    """
    key: AiEmployeeSkill_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AiEmployeeSkill_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: AiEmployeeSkill_Data!
  ): AiEmployeeSkill_KeyOutput @fdc_generated(from: "AiEmployeeSkill", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `BusinessGoal` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `BusinessGoal` or `null` if not found.
  """
  businessGoal_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: BusinessGoal_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: BusinessGoal_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: BusinessGoal_Data!
  ): BusinessGoal_KeyOutput @fdc_generated(from: "BusinessGoal", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `DeploymentRequest` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `DeploymentRequest` or `null` if not found.
  """
  deploymentRequest_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DeploymentRequest_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DeploymentRequest_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: DeploymentRequest_Data!
  ): DeploymentRequest_KeyOutput @fdc_generated(from: "DeploymentRequest", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Purchase` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Purchase` or `null` if not found.
  """
  purchase_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Purchase_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Purchase_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Purchase_Data!
  ): Purchase_KeyOutput @fdc_generated(from: "Purchase", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Review` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Review` or `null` if not found.
  """
  review_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Review_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Review_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Review_Data!
  ): Review_KeyOutput @fdc_generated(from: "Review", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `SharedKnowledge` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `SharedKnowledge` or `null` if not found.
  """
  sharedKnowledge_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SharedKnowledge_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SharedKnowledge_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: SharedKnowledge_Data!
  ): SharedKnowledge_KeyOutput @fdc_generated(from: "SharedKnowledge", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Skill` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Skill` or `null` if not found.
  """
  skill_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Skill_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Skill_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Skill_Data!
  ): Skill_KeyOutput @fdc_generated(from: "Skill", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Task` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Task` or `null` if not found.
  """
  task_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Task_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Task_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Task_Data!
  ): Task_KeyOutput @fdc_generated(from: "Task", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `AgentTask` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  agentTask_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: AgentTask_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: AgentTask_Data!
  ): Int! @fdc_generated(from: "AgentTask", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `AiEmployee` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  aiEmployee_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: AiEmployee_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: AiEmployee_Data!
  ): Int! @fdc_generated(from: "AiEmployee", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `AiEmployeeSkill` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  aiEmployeeSkill_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: AiEmployeeSkill_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: AiEmployeeSkill_Data!
  ): Int! @fdc_generated(from: "AiEmployeeSkill", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `BusinessGoal` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  businessGoal_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: BusinessGoal_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: BusinessGoal_Data!
  ): Int! @fdc_generated(from: "BusinessGoal", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `DeploymentRequest` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  deploymentRequest_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: DeploymentRequest_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: DeploymentRequest_Data!
  ): Int! @fdc_generated(from: "DeploymentRequest", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Purchase` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  purchase_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Purchase_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Purchase_Data!
  ): Int! @fdc_generated(from: "Purchase", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Review` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  review_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Review_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Review_Data!
  ): Int! @fdc_generated(from: "Review", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `SharedKnowledge` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  sharedKnowledge_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: SharedKnowledge_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: SharedKnowledge_Data!
  ): Int! @fdc_generated(from: "SharedKnowledge", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Skill` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  skill_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Skill_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Skill_Data!
  ): Int! @fdc_generated(from: "Skill", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Task` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  task_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Task_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Task_Data!
  ): Int! @fdc_generated(from: "Task", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `AgentTask` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  agentTask_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AgentTask_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AgentTask_FirstRow
  ): AgentTask_KeyOutput @fdc_generated(from: "AgentTask", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `AiEmployee` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  aiEmployee_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AiEmployee_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AiEmployee_FirstRow
  ): AiEmployee_KeyOutput @fdc_generated(from: "AiEmployee", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `AiEmployeeSkill` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  aiEmployeeSkill_delete(
    """
    The key used to identify the object.
    """
    key: AiEmployeeSkill_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AiEmployeeSkill_FirstRow
  ): AiEmployeeSkill_KeyOutput @fdc_generated(from: "AiEmployeeSkill", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `BusinessGoal` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  businessGoal_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: BusinessGoal_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: BusinessGoal_FirstRow
  ): BusinessGoal_KeyOutput @fdc_generated(from: "BusinessGoal", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `DeploymentRequest` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  deploymentRequest_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DeploymentRequest_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DeploymentRequest_FirstRow
  ): DeploymentRequest_KeyOutput @fdc_generated(from: "DeploymentRequest", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Purchase` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  purchase_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Purchase_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Purchase_FirstRow
  ): Purchase_KeyOutput @fdc_generated(from: "Purchase", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Review` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  review_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Review_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Review_FirstRow
  ): Review_KeyOutput @fdc_generated(from: "Review", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `SharedKnowledge` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  sharedKnowledge_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SharedKnowledge_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SharedKnowledge_FirstRow
  ): SharedKnowledge_KeyOutput @fdc_generated(from: "SharedKnowledge", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Skill` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  skill_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Skill_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Skill_FirstRow
  ): Skill_KeyOutput @fdc_generated(from: "Skill", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Task` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  task_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Task_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Task_FirstRow
  ): Task_KeyOutput @fdc_generated(from: "Task", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `AgentTask` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  agentTask_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: AgentTask_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "AgentTask", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `AiEmployee` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  aiEmployee_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: AiEmployee_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "AiEmployee", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `AiEmployeeSkill` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  aiEmployeeSkill_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: AiEmployeeSkill_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "AiEmployeeSkill", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `BusinessGoal` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  businessGoal_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: BusinessGoal_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "BusinessGoal", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `DeploymentRequest` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  deploymentRequest_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: DeploymentRequest_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "DeploymentRequest", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Purchase` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  purchase_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Purchase_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Purchase", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Review` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  review_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Review_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Review", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `SharedKnowledge` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  sharedKnowledge_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: SharedKnowledge_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "SharedKnowledge", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Skill` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  skill_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Skill_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Skill", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Task` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  task_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Task_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Task", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
