-- =====================================================
-- Enhanced Business Profile for Advanced AI Employee Integration
-- Adds more detailed business context for autonomous employees
-- =====================================================

-- Add new columns to business_profiles
ALTER TABLE public.business_profiles 
ADD COLUMN IF NOT EXISTS brand_voice VARCHAR(100),
ADD COLUMN IF NOT EXISTS unique_value_proposition TEXT,
ADD COLUMN IF NOT EXISTS key_products JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS key_services JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS competitors JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS pricing_model TEXT,
ADD COLUMN IF NOT EXISTS key_challenges JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS ideal_customer_profile TEXT,
ADD COLUMN IF NOT EXISTS social_media JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS annual_revenue_range VARCHAR(50),
ADD COLUMN IF NOT EXISTS employee_count VARCHAR(50),
ADD COLUMN IF NOT EXISTS founding_year INTEGER,
ADD COLUMN IF NOT EXISTS location TEXT,
ADD COLUMN IF NOT EXISTS mission_statement TEXT,
ADD COLUMN IF NOT EXISTS core_values JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS content_tone TEXT,
ADD COLUMN IF NOT EXISTS primary_keywords JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS sales_cycle_length VARCHAR(50),
ADD COLUMN IF NOT EXISTS average_deal_size VARCHAR(50),
ADD COLUMN IF NOT EXISTS main_acquisition_channels JSONB DEFAULT '[]'::jsonb;

-- Add comments for clarity
COMMENT ON COLUMN public.business_profiles.brand_voice IS 'Tone and style for all communications: professional, friendly, bold, etc.';
COMMENT ON COLUMN public.business_profiles.unique_value_proposition IS 'What makes this business unique - key differentiator';
COMMENT ON COLUMN public.business_profiles.key_products IS 'Array of main products with names, descriptions, and prices';
COMMENT ON COLUMN public.business_profiles.key_services IS 'Array of main services offered';
COMMENT ON COLUMN public.business_profiles.competitors IS 'Array of competitor names and notes about them';
COMMENT ON COLUMN public.business_profiles.pricing_model IS 'How the business charges: subscription, one-time, freemium, etc.';
COMMENT ON COLUMN public.business_profiles.key_challenges IS 'Main business challenges the AI employees should help with';
COMMENT ON COLUMN public.business_profiles.ideal_customer_profile IS 'Detailed description of ideal customer';
COMMENT ON COLUMN public.business_profiles.social_media IS 'Social media handles: {twitter, linkedin, instagram, facebook, etc.}';
COMMENT ON COLUMN public.business_profiles.sales_cycle_length IS 'How long from lead to close: days, weeks, months';
COMMENT ON COLUMN public.business_profiles.average_deal_size IS 'Typical deal value range';
COMMENT ON COLUMN public.business_profiles.main_acquisition_channels IS 'Where customers come from: SEO, paid ads, referrals, etc.';

-- Create table for storing employee work queue (autonomous task scheduling)
CREATE TABLE IF NOT EXISTS public.employee_work_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  employee_id UUID REFERENCES public.deployed_employees(id) ON DELETE CASCADE,
  template_id VARCHAR(100),
  task_type VARCHAR(50) NOT NULL, -- research, analyze, create, optimize, report
  task_title VARCHAR(255) NOT NULL,
  task_description TEXT,
  priority INTEGER DEFAULT 5, -- 1-10, 10 being highest
  scheduled_for TIMESTAMPTZ,
  status VARCHAR(50) DEFAULT 'pending', -- pending, in_progress, completed, failed
  result TEXT,
  context JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ
);

ALTER TABLE public.employee_work_queue ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own work queue" ON public.employee_work_queue
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can manage own work queue" ON public.employee_work_queue
  FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Service role full access to work queue" ON public.employee_work_queue
  FOR ALL USING (auth.role() = 'service_role');

-- Index for efficient querying
CREATE INDEX IF NOT EXISTS idx_work_queue_user_status ON public.employee_work_queue(user_id, status);
CREATE INDEX IF NOT EXISTS idx_work_queue_scheduled ON public.employee_work_queue(scheduled_for) WHERE status = 'pending';

-- Create table for daily/weekly reports generated by employees
CREATE TABLE IF NOT EXISTS public.employee_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  employee_id UUID REFERENCES public.deployed_employees(id) ON DELETE CASCADE,
  template_id VARCHAR(100),
  report_type VARCHAR(50) NOT NULL, -- daily_summary, weekly_report, monthly_analysis, ad_hoc
  title VARCHAR(255) NOT NULL,
  summary TEXT,
  full_report TEXT,
  key_findings JSONB DEFAULT '[]'::jsonb,
  action_items JSONB DEFAULT '[]'::jsonb,
  metrics JSONB DEFAULT '{}'::jsonb,
  period_start TIMESTAMPTZ,
  period_end TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.employee_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own reports" ON public.employee_reports
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Service role full access to reports" ON public.employee_reports
  FOR ALL USING (auth.role() = 'service_role');

CREATE INDEX IF NOT EXISTS idx_employee_reports_user ON public.employee_reports(user_id, created_at DESC);
