type User @table {
  displayName: String!
  email: String! @unique
  createdAt: Timestamp!
  organizationName: String
  profilePictureUrl: String
}

type AIEmployee @table {
  user: User!
  name: String!
  type: String!
  status: String!
  createdAt: Timestamp!
  description: String
}

type Skill @table {
  name: String! @unique
  description: String!
  category: String!
  isPredefined: Boolean!
  inputSchema: String
  outputSchema: String
}

type AIEmployeeSkill @table(key: ["aiEmployee", "skill"]) {
  aiEmployee: AIEmployee!
  skill: Skill!
  enabled: Boolean!
  configuration: String
}

type Task @table {
  aiEmployee: AIEmployee!
  user: User!
  status: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
  inputData: String
  outputData: String
  skillUsed: Skill
  dueDate: Timestamp
}
